[배민팀 백엔드]app 생성 및 모델 작성완료
wecode-bootcamp-korea/baemin_store-backend pull request #1
Opened 2021-01-12 19:59 UTC by jungzi1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user app 생성
- product app 생성
- order app 생성
- user, product, order의 models.py 작성 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-13 10:42 UTC, lordmyshepherd requested changes

2021-01-13 10:42 UTC, lordmyshepherd commented on order/models.py
> +  deliver     = models.ForeignKey('user.Address',    on_delete = models.CASCADE)
field명은 Class명과 동일하게 수정해주세요~
```suggestion
  address     = models.ForeignKey('user.Address',    on_delete = models.CASCADE)
```

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +	user          = models.ForeignKey('user.User', on_delete=models.CASCADE)
상품에서 user를 참조하고 있는 이유가 있나요?

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +	update_at     = models.DateTimeField(auto_now=True)
기본 `price`는 없나요?

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +	tag_id  = models.ForeignKey('Tag', on_delete=models.CASCADE)
필드명을 ₩tag_id`로 선언하면, database에 `tag_id_id`로 생성됩니다.
그렇기 때문에 아래와 같이 수정해주세요~ 
```suggestion
	tag  = models.ForeignKey('Tag', on_delete=models.CASCADE)
```

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +	tag_name = models.CharField(max_length=45)
```suggestion
	name = models.CharField(max_length=45)
```

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +	name 		= models.CharField(max_length=45)
여기서 name은 어떤 용도로 사용되는 필드인가요?

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +	tag_id  = models.ForeignKey('Tag', on_delete=models.CASCADE)
ManyToMany 관계는 Django의 ManyToManyField를 활용해서 만들어주세요~
[참고] https://docs.djangoproject.com/en/3.1/ref/models/fields/#manytomanyfield
![스크린샷 2021-01-13 오후 7 38 21](https://user-images.githubusercontent.com/53214510/104441355-e5b2e180-55d6-11eb-8354-8fe777a0af74.png)

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +    db_table  = 'likes'
Align을 맞춰주세요~

2021-01-13 10:42 UTC, lordmyshepherd commented on product/models.py
> +  update_at   = models.DateField(auto_now     = True)
마찬가지 입니다~

2021-01-13 10:42 UTC, lordmyshepherd commented on user/models.py
> +  address   = models.CharField(max_length   = 100)
나중에 ORM을 활용해서 주소를 조회할 때, Address.address 속성으로 접근해야된다. 가독성을 위해서 Address.name으로 접근할 수 있게 수정해주세요~
```suggestion
  name   = models.CharField(max_length   = 100)
```

2021-01-13 10:52 UTC, jungzi1 commented on product/models.py
> +	user          = models.ForeignKey('user.User', on_delete=models.CASCADE)
user 참조할 이유 없었습니다!! 
대신 price라는 필드가 빠져있었습니다. 잡아주셔서 감사합니다~ 수정하였습니다.🙇🏻‍♂️

2021-01-13 10:54 UTC, jungzi1 commented on order/models.py
> +  deliver     = models.ForeignKey('user.Address',    on_delete = models.CASCADE)
수정 완료했습니다!! 감사합니다 🙇🏻‍♂️

2021-01-13 10:54 UTC, jungzi1 commented on product/models.py
> +	update_at     = models.DateTimeField(auto_now=True)
누락됐습니다!! 잡아주셔서감사합니다 🙇🏻‍♂️

2021-01-13 10:56 UTC, jungzi1 commented on product/models.py
> +	tag_name = models.CharField(max_length=45)
수정했습니다 🙇🏻‍♂️

2021-01-13 10:58 UTC, jungzi1 commented on product/models.py
> +	name 		= models.CharField(max_length=45)
잘못 입력된 것 같습니다 ㅜㅜ  잡아주셔서 감사합니다.🙇🏻‍♂️

2021-01-13 10:59 UTC, jungzi1 commented on product/models.py
> +    db_table  = 'likes'
맞추겠습니다 감사합니다 🙇🏻‍♂️

2021-01-13 11:00 UTC, jungzi1 commented on product/models.py
> +  update_at   = models.DateField(auto_now     = True)
저희 로컬 상에는 맞는데 왜 안맞을까요? ㅜㅜ 일단 다시 커밋해보겠습니다

2021-01-13 16:59 UTC, hyeseong-dev commented on product/models.py
> +	update_at     = models.DateTimeField(auto_now=True)
에궁 누락 ㅠ.ㅠ

2021-01-13 17:02 UTC, hyeseong-dev commented on product/models.py
> +	tag_name = models.CharField(max_length=45)
😁🤗

2021-01-13 17:02 UTC, hyeseong-dev commented on product/models.py
> +	name 		= models.CharField(max_length=45)
😭

2021-01-13 17:02 UTC, hyeseong-dev commented on product/models.py
> +    db_table  = 'likes'
😅

2021-01-13 17:03 UTC, hyeseong-dev commented on product/models.py
> +  update_at   = models.DateField(auto_now     = True)
😅 꼼꼼함!

2021-01-14 01:53 UTC, lordmyshepherd requested changes

2021-01-14 01:53 UTC, lordmyshepherd commented on product/models.py
> +	sales 		  = models.ManyToManyField('Sale', through='ProductSale')
Align이 맞지를 않네요~ 수정해주세요~

2021-01-14 01:54 UTC, lordmyshepherd commented
LGTM 👍

2021-01-14 01:54 UTC, merged