[16기 이혜성]Add : user views, url, utils😉
wecode-bootcamp-korea/baemin_store-backend pull request #3
Opened 2021-01-14 20:03 UTC by hyeseong-dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한 줄 요약
(여기에 수정 사항에 대한 간략한 한 줄 요약/제목 작성해 주세요.)

회원 가입, 로그인 View 작성 완료 

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

<user app>
- views.py
  - `SignUpView`, `LoginView` 추가

-  decorator/utils.py
  - 인증, 인가에 대한 부분을 모듈화하여 작성
  - DB에 존재하는 정보도 잡아내기(account, email, name, phone)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

>회원 가입 구현 Logic을 더 깔끔하게 작성하고 싶습니다. 
혹시 중복되는 부분이 있을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-15 03:02 UTC, lordmyshepherd requested changes

2021-01-15 03:02 UTC, lordmyshepherd commented on decorators/utils.py
> +    return True
validation을 위한 함수들은 decorator가 아니기 때문에 decorator directory 밖에 다른 모듈로 옮겨주세요~

2021-01-15 03:02 UTC, lordmyshepherd commented on decorators/utils.py
> +    return True
마찬가지 입니다.

2021-01-15 03:02 UTC, lordmyshepherd commented on decorators/utils.py
> +            setattr(request, 'user', User.objects.get(id=['user_id']))
`line 57`에서 db에서 user 레코드를 조회해왔는데, `line 58`에서 objects.get()를 사용해서 다시 호출하시는 이유가 있나요?
```suggestion
            setattr(request, 'user', User.objects.get(id=['user_id']))
```

2021-01-15 03:02 UTC, lordmyshepherd commented on decorators/utils.py
> +        return func(request, *args, **kwargs)
try문 안으로 넣어주세요~

2021-01-15 03:02 UTC, lordmyshepherd commented on user/views.py
> +                return utils.password_check(password)
`utils.password_check`에서 에러를 핸들링 해주고 있으니, 여기서는 password_check를 호출만하면 되지않나요?
if 문을 지워주세요~

2021-01-15 03:02 UTC, lordmyshepherd commented on user/views.py
> +                    return JsonResponse({'TOKEN':user_token}, status=200)
token이 어떤 token인지 정확히 명시해주는게 좋습니다.
나중에 refresh_token등 다양한 토큰을 관리해야될 수 있습니다.

2021-01-15 03:02 UTC, lordmyshepherd commented on user/views.py
> +            signup_db   = User.objects.all()
지워주셔도 될 것 같습니다~
```suggestion
            signup_db   = User.objects.all()
```

2021-01-15 03:45 UTC, hyeseong-dev commented on decorators/utils.py
> +    return True
병민님 감사합니다!😙
다른 모듈로 옮기도록 하겠습니다.

2021-01-15 03:45 UTC, hyeseong-dev commented on decorators/utils.py
> +    return True
네에~!!

2021-01-15 03:48 UTC, hyeseong-dev commented on decorators/utils.py
> +            setattr(request, 'user', User.objects.get(id=['user_id']))
중간에 코드 변경하고(위스타 그램에서는  `setattr()` 메서드를 사용(x) ) 리팩토링하지 않아서 생긴 부분이에요.
feedback 주셔서감사합니다.

2021-01-15 04:05 UTC, hyeseong-dev commented on decorators/utils.py
> +        return func(request, *args, **kwargs)
네! 안으로 바로 넣었습니다. 
그리고  아래부분도 누락하여 추가하였습니다.

```python
  except User.DoesNotExist:
            return JsonResponse({"message":"USER_DOES_NOT_EXIST"}, status = 401)
```

2021-01-15 10:25 UTC, hyeseong-dev commented on user/views.py
> +                return utils.password_check(password)
```python
utils.password(password)
```

2021-01-15 10:26 UTC, hyeseong-dev commented on user/views.py
> +                return utils.password_check(password)
feedback 주신 부분 반영하여 함수 호출만 하였습니다.

2021-01-15 10:28 UTC, hyeseong-dev commented on user/views.py
> +            signup_db   = User.objects.all()
네에~!

2021-01-15 10:28 UTC, hyeseong-dev commented on user/views.py
> +                    return JsonResponse({'TOKEN':user_token}, status=200)
토큰이름을 변경하도록 하겠습니다.

2021-01-19 02:59 UTC, lordmyshepherd commented
나중에 유효한 휴대폰 번호 validation을 구현하실 때, 참고해주시면 좋을 것 같아서 코드 남겨놓습니다.

```python
def get_phone_number(buyer_phone, buyer_cellphone):
    phone = (buyer_phone or '').replace('-', '')
    if phone and len(phone) == 11 and phone[:3] in ['010', '011', '016', '017', '019']:
        return phone
    return ''
```

2021-01-19 03:00 UTC, lordmyshepherd commented
LGTM 👍

2021-01-19 03:00 UTC, merged