ProductsListView(category별, sorting method별 list 정렬)
wecode-bootcamp-korea/baemin_store-backend pull request #4
Opened 2021-01-18 07:51 UTC by jungzi1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 제품 list 페이지에 노출 되는 제품 리스트 전달,
- page 별 제품 갯수(16개)에 맞는 2차원 배열로 프론트 전달
- rest api get parameter에 입력되는 category code별 리스트 filter
- rest api get parameter에 입력되는 sorting method string별 리스트 정렬

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- filter된 제품 dictionary를 16개씩 리스트로 묶어 요청 응답
- sorting method[default, high/low price, new(데이터 입력된 순서대로)]를 사전에 약속된 스트링을 rest api get parameter로 받아 sort() 매서드레 key 값의 value 값으로 정렬

## 기타 질문 및 특이 사항
- sale이나 기타 tag status를 제품별로 입력하여 같이 전달을 주는 로직을 앞으로 구현할 기획입니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-19 23:44 UTC, hyeseong-dev commented
지현님 conflicts 해결 부탁드려요.

2021-01-20 02:18 UTC, lordmyshepherd requested changes

2021-01-20 02:18 UTC, lordmyshepherd commented on baemin/urls.py
> +    path('product', include('product.urls'))
`URI` 첫번째 계층은 복수명사로 만들어주세요.
Ex)
```
/products
/users
```

2021-01-20 02:18 UTC, lordmyshepherd commented on decorators/utils.py
> +import jwt
해당 파일에 대한 리뷰는 이전 pr에 반영된 내용을 적용해주세요~

2021-01-20 02:18 UTC, lordmyshepherd commented on product/views.py
> +            #         )
주석은 지워주세요~

2021-01-20 02:18 UTC, lordmyshepherd commented on product/views.py
> +    # @login_required
상품 리스트를 반환하는 엔드포인트에 로그인데코레이터가 필요한가요?

2021-01-20 02:18 UTC, lordmyshepherd commented on product/views.py
> +            items_per_page = 16
해당 엔드포인트를 필요로하는 모든 페이지에서 16개를 기본으로 한다고 하면 상관없지만, `API`는 여러 곳에서 호출해서 사용될 수 있도록 만들어주셔야 합니다.
`query parameter`를 사용해서 `offset`과 `limit`을 받아서 구현해주세요. (페이지네이션 기능)

```suggestion

```

2021-01-20 02:18 UTC, lordmyshepherd commented on product/views.py
> +    def get(self,request, catCd, sorting):
catCd <- 값은 어떤 값인가요?
```suggestion
    def get(self,request, catCd, sorting):
```

2021-01-20 02:18 UTC, lordmyshepherd commented on product/views.py
> +    def get(self,request, catCd, sorting):
sorting 기능은 `path parameter`가 아니라 `query parameter`를 사용해서 구현해주세요~
```suggestion
    def get(self,request, catCd, sorting):
```

2021-01-20 02:18 UTC, lordmyshepherd commented on pull_request_template.md
> +>>>>>>> main
컨플릭트 해결해주세요~

2021-01-20 02:18 UTC, lordmyshepherd commented on product/urls.py
> +    path('/product_list/<int:catCd>/<str:sorting>', views.ProductListView.as_view()),
`URI`를 Restful하게 구현해주시면 좋을 것 같아요!
자세한 내용은 `product/views.py`에 리뷰 남겨 놓았습니다.

2021-01-20 02:18 UTC, lordmyshepherd commented on product/views.py
> +            if catCd ==0:
`catCd == 0`이 의미하는게 무엇인지 알기가 어렵습니다.
```suggestion
            if catCd ==0:
```

2021-01-20 02:19 UTC, lordmyshepherd commented
컨플릭트도 해결해주세요~

2021-01-20 02:31 UTC, jungzi1 commented on product/views.py
> +    def get(self,request, catCd, sorting):
네 병민님! category id 값입니다! URI parameter로 받아서 해당 카테고리에 해당하는 상품들을 필터링 해주기 위해서 사용했습니다. 조금더 직관적이게 catId식으로 이름을 바꿔 보겠습니다

2021-01-20 02:33 UTC, jungzi1 commented on product/views.py
> +            if catCd ==0:
전체를 선택할 경우 카테고리 상관없이 모든 상품을 필터링하기 위해 넣어 놨습니다.

2021-01-20 02:33 UTC, jungzi1 commented on baemin/urls.py
> +    path('product', include('product.urls'))
네 변경하겠습니다!

2021-01-20 02:35 UTC, jungzi1 commented on product/views.py
> +    # @login_required
아니요! 필요없어서 주석 처리 하였습니다. 필요없는 주석 지워주도록 하겠습니다~

2021-01-20 02:35 UTC, jungzi1 commented on product/views.py
> +            #         )
네 지우도록 하겠습니다!

2021-01-22 02:45 UTC, lordmyshepherd requested changes

2021-01-22 02:45 UTC, lordmyshepherd commented on decorators/utils.py
> +        return JsonResponse({'MESSAGE':' PASSWORD SHOULD BE OVER 8 AND UNDER 17 '}, status=412)
`password_check`, `phone_validation`, `username_validation`, `account_validation` 함수는 데코레이터가 아니기 때문에 `/decorators/utiles.py` 위치가 아니라 `/utils.py` 위치로 옮겨주세요~

2021-01-22 02:45 UTC, lordmyshepherd commented on product/urls.py
> +    path('/product_list/<int:categoryId>/<str:sorting>', views.ProductListView.as_view()),
`RESTful`하게 엔드포인트를 구현하기 위해서는 위에 URI를 수정해야 합니다.
아래와 같이 URI를 만들어주셔야 합니다.
```python
GET /products?categoryId=1&sorting=-price
```
1단계) 그러기 위해서는 아래와 같이 urls.py를 수정해주세요.
```suggestion
    path('', views.ProductListView.as_view()),
```
2단계) View 수정
http request message의 body = request.body
(1) path paramter 
```python 
in urls.py
    path('<int:product_id>', views.ProductListView.as_view()),
in views.py
   def get(self, request, product_id):
```
(2) query parameter
```python 
in urls.py
    path('', views.ProductListView.as_view()),
in views.py
   def get(self, request):
       category_id = request.GET["categoryId"]
                                              GET.getlist()
      
```

2021-01-23 11:01 UTC, jungzi1 commented on decorators/utils.py
> +import jwt
넵 수정하겠습니다!

2021-01-23 11:02 UTC, jungzi1 commented on product/views.py
> +    def get(self,request, catCd, sorting):
감사합니다 쿼피 파라미터를 익혀서 다음 프로젝트때 더욱 유연하게 사용할수 있도록 연습해보겠습니다!

2021-01-23 11:02 UTC, jungzi1 commented on product/urls.py
> +    path('/product_list/<int:catCd>/<str:sorting>', views.ProductListView.as_view()),
query parameter로 수정하였습니다!! 감사합니다 병민님~

2021-01-23 11:03 UTC, jungzi1 commented on decorators/utils.py
> +        return JsonResponse({'MESSAGE':' PASSWORD SHOULD BE OVER 8 AND UNDER 17 '}, status=412)
'users/utils.py로  이동시켰습니다!!

2021-01-23 11:04 UTC, jungzi1 commented on product/urls.py
> +    path('/product_list/<int:categoryId>/<str:sorting>', views.ProductListView.as_view()),
감사합니다 병민님!! RESTful한 qpi에 신경 쓰도록 하겠습니다.

2021-01-29 17:00 UTC, merged